name: Deploy Infinity

on:
  workflow_call:
    inputs:
      path:
        type: string
        description: Path to the terraform code that deploys Infinity
        default: ./integration_test/

permissions: {}

env:

jobs:
  install:
    name: Deploy Infinity
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Show current gcloud user
        run: gcloud config list account --format "value(core.account)"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "1.6"
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check -recursive ${inputs.path}

      - name: Terraform init
        run: terraform init
        working-directory: ${inputs.path}

      - name: Terraform apply
        run: terraform apply -no-color -auto-approve
        working-directory: ${inputs.path}
