name: Destroy Infinity

on:
  workflow_call:
    inputs:
      path:
        type: string
        description: Path to the terraform code that deploys Infinity
        required: true

permissions: {}

jobs:
  install:
    name: Destroy Infinity
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: pexip/shared-github-actions/auth-gcp-action@1d23017a5082a03cd73bb254fd8da5be60228c8a
        id: auth-gcp
        with:
          service_account_key: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}

      - name: Terraform destroy
        run: terraform destroy -no-color -auto-approve
        working-directory: ${inputs.path}
