name: Destroy Infinity

on:
  workflow_call:
    inputs:
      path:
        type: string
        description: Path to the terraform code that deploys Infinity
        required: true

permissions: {}

jobs:
  install:
    name: Destroy Infinity
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Terraform variables
        shell: bash
        run: |
          echo "TF_VAR_project_id=${{ vars.DEPLOY_PROJECT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_environment=${{ vars.ENVIRONMENT || 'dev' }}" >> $GITHUB_ENV
          echo "TF_VAR_infinity_contact_email_address=${{ vars.INFINITY_CONTACT_EMAIL_ADDRESS }}" >> $GITHUB_ENV
          echo "TF_VAR_infinity_password=${{ secrets.INFINITY_ADMIN_PASSWORD }}" >> $GITHUB_ENV
          echo "TF_VAR_infinity_license_key=${{ secrets.INFINITY_LICENSE_KEY }}" >> $GITHUB_ENV
      - uses: pexip/shared-github-actions/auth-gcp-action@f596d7f32b05fa5ffebbb6634734860d5d1d6c2c
        id: auth-gcp
        with:
          service_account_key: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}
      - uses: pexip/shared-github-actions/terraform-destroy-gcp-action@f596d7f32b05fa5ffebbb6634734860d5d1d6c2c
        with:
          directory: ${{ inputs.path }}